# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Install modules
  - npm ci

cache:
  - '%APPDATA%\npm-cache'
  - node_modules

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

  # Run tests
  - npm test

  # Install hooks locally
  - npm run devinstall
  - cat .git/hooks/post-checkout

  # Test HUSKY_SKIP_HOOKS
  - $env:HUSKY_SKIP_HOOKS=1 git checkout
  - node scripts/ci-husky-skip-hooks-check

  # Test post-checkout hook
  - git checkout
  - node scripts/ci-post-checkout-check

  # Should not fail due to missing script
  - node scripts/ci-break-path.js
  - git checkout

  # Test uninstall
  - npm run devuninstall

# Don't actually build.
build: off
